import { 
  Cloud, FileText, Image as ImageIcon, PieChart, Shield, Calendar, 
  Globe, Mail, Music, Video, Code, Database, Terminal, Folder,
  AppWindow, Box, Briefcase, Calculator, Camera, Cast,
  CheckSquare, Coffee, CreditCard, DollarSign, Figma, 
  Github, Headphones, Heart, Home, Layout, Link, 
  Lock, Map, MessageCircle, Mic, Monitor, Moon,
  Package, PenTool, Phone, Play, Printer, Radio,
  Save, Server, ShoppingBag, ShoppingCart, Slack,
  Smartphone, Speaker, Star, Sun, Table, Tag,
  Wrench, Trash, Truck, Tv, Twitch, Twitter,
  User, Users, Wifi, Youtube, Zap
} from 'lucide-react';

export const iconMap: Record<string, any> = {
  'Cloud': Cloud,
  'FileText': FileText,
  'Image': ImageIcon,
  'PieChart': PieChart,
  'Shield': Shield,
  'Calendar': Calendar,
  'Globe': Globe,
  'Mail': Mail,
  'Music': Music,
  'Video': Video,
  'Code': Code,
  'Database': Database,
  'Terminal': Terminal,
  'Folder': Folder,
  'AppWindow': AppWindow,
  'Box': Box,
  'Briefcase': Briefcase,
  'Calculator': Calculator,
  'Camera': Camera,
  'Cast': Cast,
  'CheckSquare': CheckSquare,
  'Coffee': Coffee,
  'CreditCard': CreditCard,
  'DollarSign': DollarSign,
  'Figma': Figma,
  'Github': Github,
  'Headphones': Headphones,
  'Heart': Heart,
  'Home': Home,
  'Layout': Layout,
  'Link': Link,
  'Lock': Lock,
  'Map': Map,
  'MessageCircle': MessageCircle,
  'Mic': Mic,
  'Monitor': Monitor,
  'Moon': Moon,
  'Package': Package,
  'PenTool': PenTool,
  'Phone': Phone,
  'Play': Play,
  'Printer': Printer,
  'Radio': Radio,
  'Save': Save,
  'Server': Server,
  'ShoppingBag': ShoppingBag,
  'ShoppingCart': ShoppingCart,
  'Slack': Slack,
  'Smartphone': Smartphone,
  'Speaker': Speaker,
  'Star': Star,
  'Sun': Sun,
  'Table': Table,
  'Tag': Tag,
  'Tool': Wrench,
  'Trash': Trash,
  'Truck': Truck,
  'Tv': Tv,
  'Twitch': Twitch,
  'Twitter': Twitter,
  'User': User,
  'Users': Users,
  'Wifi': Wifi,
  'Youtube': Youtube,
  'Zap': Zap
};

export const getIcon = (iconName: string) => {
  return iconMap[iconName] || AppWindow;
};

export const getIconNames = () => Object.keys(iconMap).sort();